### ISSUE TITLE
META: Missing Official Mech Equipment

### ISSUE THREAD

**Issue by WEKarnesky** [Solaris-Skunk-Werks/solarisskunkwerks#24]
The following official equipment needs to be implemented in SSW:

## Ballistic
- [ ] Gauss Rifle (Prototype) (IS, Pg72 IO)
- [ ] Imp.AC/2 (Clan, Pg96 IO)
- [ ] Imp.AC/5 (Clan, Pg96 IO)
- [ ] Imp.AC/10 (Clan, Pg96 IO)
- [ ] Imp.AC/20 (Clan, Pg96 IO)
- [ ] Imp.Gauss Rifle (Clan, Pg96 IO)
- [ ] LB-02-X AC (Prototype) (Clan, Pg97 IO)
- [ ] LB-05-X AC (Prototype) (IS, Pg 72 IO)
- [ ] LB-10-X AC (Prototype) (Clan, Pg97 IO)
- [ ] LB-20-X AC (Prototype) (Clan, Pg97 IO)
- [ ] Light AC/2 (IS, Pg207 TechManual)
- [ ] Light AC/5 
- [ ] Ultra AC/2 (Prototype) (Clan, Pg98 IO)
- [ ] Ultra AC/5 (Prototype) (IS, Pg 104 IO)
- [ ] Ultra AC/10 (Prototype) (Clan, Pg98 IO)
- [ ] Ultra AC/20 (Prototype) (Clan, Pg98 IO)
## Energy
- [ ] Centurion Weapon System (IS, Pg85 IO)
- [ ] Enhanced PPC (Clan, Pg95 IO) 
- [ ] Improved PPC (Clan, Pg95 IO)
- [ ] ER Large Laser (Prototype) (IS, Pg103 IO)
- [ ] Medium Pulse Laser (Prototype) (IS, Pg103 IO)
- [ ] RISC Hyper Laser (IS, Pg93 IO)
- [ ] RISC Repeating TSEMP (IS, Pg94 IO)
## Missile
- [ ] Rocket Launcher 10 (Prototype) (IS, Pg217 IO)
- [ ] Rocket Launcher 15 (Prototype) (IS, Pg217 IO)
- [ ] Rocket Launcher 20 (Prototype) (IS, Pg217 IO)
## Missile Ammo
- [ ] Anti-TSM
- [ ] Dead-Fire
- [ ] Listen-Kill

**Comment by Maelwys** [comment]
Wait, since when has this been missing LACs? They've been in it forever.

**Comment by WEKarnesky** [comment]
Probably snuck in due to how we crowdsourced the missing equipment.  I marked them as done.

**Comment by Maelwys** [comment]
IO says that for Prototype equipment they have "Standard Production" dates, which is when the non-Prototype version goes into production, and "After this standard production date, the prototype versions featured here will gradually phased out of service, mostly retired after a decade."

So should we set the extinction date on the Prototypes to "Standard" or "Standard +10" ?

**Comment by WEKarnesky** [comment]
In order:

1: I think Standard + 10 will be more useful to people, so we should go with that

2: I would say it depends on availability. I think the system can only do one extinction date, so to work around that we would have to have it as two entries, even if they are the same.

3: We should stick to the CGL's standard, even if I would prefer a more user-friendly notation.

**Comment by Maelwys** [comment]
1. Alright.

2. Yeah, didn't think about the second extinction date.

3. Ug. Alright. What's funny is alot of them have better notations in the book (like GR-P and Gauss-X for the), but I'll stick to standard notation. HOpefully I'll have the two GRs and their ammo done by tomorrow.

**Comment by WEKarnesky** [comment]
If the Book says GR-P and Gauss-X we can use that.  Books are the first and primary source of all our references for anything we do.

**Comment by Maelwys** [comment]
The Centurion Weapon System is a bit tricky because its Type is "DE, E" which makes it both a Direct Energy Weapon and a piece of Equipment, and I'm honestly not sure how SSW would handle trying to have an DE,E for the Type in the Type section for the item.

**Comment by VhenRa** [comment]
Isn't Centurion already in SSW? 

The rocket launchers are a fairly trivial change, they are identical stats wise to the pentagon rocket launchers from Operation Klondike or the ones from Reunification War, so they just need a couple of internal values changed from existing files.

The Enhanced PPC is already in SSW, it is just a new name for the Enhanced ERPPC from Jihad Secrets, so that's just a case of changing a couple of lines in the equipment file. Though doing so will break any designs which used the old name.

The people behind this already have a good starting point file for the early clan improved weapons, so those should be in progress. The early clan UACs and LBXs are easily doable, just gotta figure out [how] to implement them. [Naming is gonna be the fun part]

The IS prototype weapons, now those are mainly just a copy, paste and edit job for existing versions of them. I could probably rig up the Gauss-X and prototype pulse lasers in an afternoon.

**Comment by Maelwys** [comment]
I thought it was under Equipment. The problem is I have a build copy of SSW from when Skyhigh and I were occasionally working on it, so I'm not always sure what made it to public and what didn't (I suppose I could download an older version to check).

I was taking most of this on faith. I know the Prototype stuff isn't in (or atleast not all of it). And we've got the oddly named CI and CP Autocannons, so some of them might just need tweaking...

I've got the Enhanced and improved PPCs done in an excel file (I think done right) and most of the GR-P (realized later that I'd have to make an ammo for it since its ammo doesn't cost the same as a the basic version).

Can I just say IO sort of sucks layout wise?

**Comment by VhenRa** [comment]
Yeah, I have the clan improved weapons mostly done and provided as such to the devteam. [Improved ACs, Improved GR, Improved PPC, Improved LRM and SRM, that sorta stuff]. 
My versions are probably a little clunkier then I would prefer and were basically just for my own use, so I didn't even try to get MM compatibility.

Their prototype LBX/Ultras need redoing somewhat. The CI stuff probably just needs deleting entirely.

**Comment by Maelwys** [comment]
Or atleast renamed/fact checked against IO.

If we do rename it all, on the plus side, if we keep the Lookup name the same, it shouldn't break things...

The ERLL-P and MPL-P might require some coding. Both of them have variable heat and heat efficiencies.

**Comment by VhenRa** [comment]
I mean, the CI stuff doesn't exist. With stuff like Era Digest Golden Century and Interstellar Operations, the full clantech versions of the LBX and Ultras were developed shortly after the prototype versions so the IS-version analogs that the CI-versions represent don't exist.

**Comment by Maelwys** [comment]
Hmm. Guess I need to look at IO closer.

**Comment by WEKarnesky** [comment]
With Regards to adding Freezers.

I think I see how to add the style that MM has, where by you get Single Heat Sink (SHS) in the engine, and Double Heat Sink (DHS) outside.

It's not clean. but the HS factory can add a few lines detect if the type isFreezer, and if so, modify the cooling provided. This would be done in `HeatSinkFactory.TotalDissipation()` which is currently at line 218.

This could be added in about the same time that the VRPP took, a couple hours or so.

However, This will not support External SHS and DHS at the same time.

That.... I'm not sure how to support with the current design of code.

**Comment by Maelwys** [comment]
Freezers  and the ER-LL-P an MPL- have already been mentioned, but there is additional equipment missing from the Inner Sphere Recovered Prototypes (Late Succession War) starting on page 102 of IO

Prototype Endo Steel, 
Prototype Ferro Fibrous
Prototype Gauss Rifle
Prototype LB10-X
Prototype TSM
Prototype UAC5

There's also additional equipment from the Advanced Prototypes Systems (Age of War) on page 70

Prototype Arrow IV
Prototype Artemis IV FCS
Prototype BAP
Prototype CASE
Prototype DHS have already been mentioned
Prototype ES
Prototype XL engine
Prototype FF
Prototype GR
Prototype GECM
Prototype LB 10-X
Prototype NARC
Prototype Pulse Lasers
Prototype Remote Sensors
Prototype RLs (this needs to be checked to make sure all the details fit with the RL-PPs from KLONDIKE)
Prototype TAG

**Comment by Maelwys** [comment]
I will make one suggestion. 

We use the naming convention of -P for the AoW Prototypes and the -X for the Succession Wars equipment to distinguish between the two. And we can copy and paste some of this, just give the copy different dates and factions and availabilities.

**Comment by WEKarnesky** [comment]
CEWS and Imp PPC are both in SSW.  CWS's availability code is E/FFFE but, according to IntOps, it should be E/FFFX.  I have not changed that yet.

**Comment by WEKarnesky** [comment]
From @Maelwys 
[Improved_PPC.xlsx](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3722751/Improved_PPC.xlsx)

**Comment by WEKarnesky** [comment]
from @VincentDegrassa 

[Custom_Equipment.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3723056/Custom_Equipment.zip)

**Comment by WEKarnesky** [comment]
The following are now in the Dev Branch:

* RISC Hyper Laser
* RISC Repeating TSEMP
* Improved PPC
* Improved Autocannon/2
* Improved Autocannon/5
* Improved Autocannon/10
* Improved Autocannon/20
* Improved Gauss Rifle
* Improved Large Laser
* Improved Large Pulse Laser
* Improved Long Range Missile-5
* Improved Long Range Missile-10
* Improved Long Range Missile-15
* Improved Long Range Missile-20
* Improved Short Range Missile-2
* Improved Short Range Missile-4
* Improved Short Range Missile-6

**Comment by VhenRa** [comment]
Latest dev release does have a slight style issue with the Improved PPC. It's listed as (Clan) Improved PPC, where the consistent style for SSW has been (CL) Improved PPC. 

I noticed an error with the iGR lacking ammo, but I have found where I made a mistake and provided a fixed version of the files. There was also a misnamed ammo for the iAC10 and iAC20, I have fixed that. My fault, quick work on my part a long time ago proliferated.

**Comment by WEKarnesky** [comment]
Updates to the ammo and weapons from @VincentDegrassa
[Custom_Equipment.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3729618/Custom_Equipment.zip)

**Comment by Xeno426** [comment]
Any chance we could see some unofficial stuff, like some of the MFUK equipment?

**Comment by WEKarnesky** [comment]
> Any chance we could see some unofficial stuff, like some of the MFUK equipment?

I'm not familiar with the MFUK equipment.  We don't have plans for unofficial equipment at this time, but simple weapons and equipment can be inserted with the included spreadsheet and BinConvert utility

**Comment by Maelwys** [comment]
The Dumper (page 243 Tech Manual) is missing from SSW and SAW.

The Ladder (245 TM) is missing as well.

**Comment by Xeno426** [comment]
> 
> 
> > Any chance we could see some unofficial stuff, like some of the MFUK equipment?
> 
> I'm not familiar with the MFUK equipment. We don't have plans for unofficial equipment at this time, but simple weapons and equipment can be inserted with the included spreadsheet and BinConvert utility

Some of the interesting ones include:
RAC/10 and RAC/20 for Clans
Rail Gun
Kinslaughter H ERPPC

**Comment by WEKarnesky** [comment]
I pushed branch feature/Dumper.  Most of the functionality is there, but there is a UI glitch that I have not been able to resolve and haven't had time to focus on it.  If someone can finish it that would be awesome.

**Comment by WEKarnesky** [comment]
Added Vehicular Mine Dispenser

**Comment by JstnB** [comment]
I don't see the Drone Control Console (from Interstellar Operations).
